#!/usr/bin/env node
/**
 * Turns the items you kept in the review screen into the issue's Proof block.
 *
 *   node newsletter/news/proof.mjs 002
 *   node newsletter/news/proof.mjs 002 > proof-block.html
 *   node newsletter/news/proof.mjs 002 --check          # verify every link resolves
 *   node newsletter/news/proof.mjs 002 --day 2026-09-01
 *
 * Report to stderr, HTML to stdout — same split as build-wwp.mjs, so
 * redirecting gives you a clean file to paste while you still see the report.
 *
 * The block it writes is deliberately incomplete. Each bullet arrives with the
 * claim, the outlet, the date and the link already wired, and the consequence
 * left as {{WHY_IT_MATTERS_n}} for you to write. The README's rule for this
 * section is one claim, one consequence, one source link: the claim and the
 * link belong to the source, the consequence is the reason anyone subscribes,
 * and a script that invented it would be inventing bourbon facts.
 *
 * Nothing is written back. This reads the run file and prints.
 */

import { readRun, runPath, latestRunPath, escapeHtml, shortDate, daysAgo, hostOf, die, w } from "./lib.mjs";
import { existsSync } from "node:fs";

// ------------------------------------------------------------------- args ---

const opts = { issue: null, path: null, check: false, allowRedirects: false };
const argv = process.argv.slice(2);
for (let i = 0; i < argv.length; i += 1) {
  const arg = argv[i];
  if (arg === "--check") opts.check = true;
  else if (arg === "--allow-redirects") opts.allowRedirects = true;
  else if (arg === "--day") opts.path = runPath(argv[++i]);
  else if (arg.startsWith("--day=")) opts.path = runPath(arg.slice(6));
  else if (!arg.startsWith("--") && !opts.issue) opts.issue = arg;
  else die(`Unknown argument "${arg}".`);
}
if (!opts.issue) {
  die("No issue given.\n         Usage: node newsletter/news/proof.mjs 002");
}
if (opts.path && !existsSync(opts.path)) die(`No run file for that day:\n         ${opts.path}`);

const RUN_PATH = opts.path ?? latestRunPath();

// ------------------------------------------------------------------ render --

/** The link the bullet cites: the publisher's own URL, never an aggregator's. */
function citationUrl(item) {
  return item.directUrl?.trim() || item.url;
}

function sourceLabel(item) {
  const outlet = item.publisher && item.publisher !== item.source ? item.publisher : item.source;
  const date = shortDate(item.published);
  return date ? `${outlet}, ${date}` : outlet;
}

/** Headlines arrive with and without terminal punctuation. Normalise to a claim. */
function lead(title) {
  const clean = title.replace(/\s+/g, " ").trim();
  return /[.!?:]$/.test(clean) ? clean : `${clean}.`;
}

function renderBullet(item, index) {
  const url = citationUrl(item);
  const note = item.angle?.trim()
    ? `\n          <!-- your angle: ${escapeHtml(item.angle.trim()).replace(/--/g, "&#45;&#45;")} -->`
    : "";

  return `      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td width="18" valign="top" style="font-family:Inter,Helvetica,Arial,sans-serif;font-size:16px;line-height:26px;color:#B0642E;font-weight:700;">&bull;</td>
          <td valign="top" style="padding-bottom:14px;font-family:Inter,-apple-system,'Segoe UI',Helvetica,Arial,sans-serif;font-size:16px;line-height:26px;color:#0E0E0E;">${note}
            <strong style="color:#0E0E0E;">${escapeHtml(lead(item.title))}</strong> {{WHY_IT_MATTERS_${index + 1}}}
            <a href="${escapeHtml(url)}" style="color:#9A5528;text-decoration:underline;">${escapeHtml(sourceLabel(item))}</a>
          </td>
        </tr>
      </table>`;
}

function render(items, run) {
  return `<!-- Proof — generated by newsletter/news/proof.mjs from run ${run.day}.
     Replace every {{WHY_IT_MATTERS_n}} with the consequence. One claim, one
     consequence, one source link. Drop this in place of the PROOF item block
     in template.html. -->
  <tr>
    <td class="sbb-pad sbb-body-text" style="padding:16px 40px 0;font-family:Inter,-apple-system,'Segoe UI',Helvetica,Arial,sans-serif;font-size:16px;line-height:26px;color:#0E0E0E;">
${items.map(renderBullet).join("\n")}
    </td>
  </tr>`;
}

// ----------------------------------------------------------------- checks ---

async function checkLinks(items) {
  const results = [];
  await Promise.all(
    items.map(async (item) => {
      const url = citationUrl(item);
      try {
        const res = await fetch(url, {
          method: "GET",
          redirect: "follow",
          headers: { "user-agent": "SmallBatchBourbon-news/1.0 (+https://smallbatchbourbon.com)" },
          signal: AbortSignal.timeout(15_000),
        });
        results.push({ url, status: res.status, ok: res.ok });
      } catch (error) {
        results.push({ url, status: error.name === "TimeoutError" ? "timed out" : error.message, ok: false });
      }
    }),
  );
  return results;
}

// ------------------------------------------------------------------- main ---

async function main() {
  const run = readRun(RUN_PATH);
  const kept = run.items.filter((i) => i.keep);

  if (!kept.length) {
    die(
      `Nothing is marked keep in ${run.day}.\n` +
        "         Open the review screen first:  node newsletter/news/review.mjs",
    );
  }

  const unlinked = kept.filter((i) => i.needsDirectLink && !i.directUrl?.trim());
  if (unlinked.length && !opts.allowRedirects) {
    die(
      `${unlinked.length} kept item${unlinked.length > 1 ? "s" : ""} still cite${
        unlinked.length > 1 ? "" : "s"
      } Google's redirector:\n` +
        unlinked.map((i) => `           - ${i.title.slice(0, 64)}`).join("\n") +
        "\n\n         Paste the publisher's own URL in the review screen — the aggregator\n" +
        "         link is not a citation, and it rots. Override with --allow-redirects.",
    );
  }

  const warnings = [];
  if (kept.length < 3) warnings.push(`${kept.length} bullets — the section budget is 3-5. A thin week is fine; three is the floor.`);
  if (kept.length > 5) warnings.push(`${kept.length} bullets — the section budget is 3-5. Cut the weakest.`);

  const stale = kept.filter((i) => (daysAgo(i.published) ?? 0) > 14);
  for (const item of stale) {
    warnings.push(`"${item.title.slice(0, 52)}" is ${daysAgo(item.published)} days old — check it hasn't been superseded.`);
  }

  const byOutlet = new Map();
  for (const item of kept) {
    const outlet = item.publisher || item.source;
    byOutlet.set(outlet, (byOutlet.get(outlet) ?? 0) + 1);
  }
  for (const [outlet, n] of byOutlet) {
    if (n > 2) warnings.push(`${n} of ${kept.length} bullets come from ${outlet}. Spread the sourcing.`);
  }

  const missingAngle = kept.filter((i) => !i.angle?.trim()).length;
  if (missingAngle) {
    warnings.push(`${missingAngle} bullet${missingAngle > 1 ? "s have" : " has"} no angle noted — you'll be writing that consequence from memory.`);
  }

  // -------- report

  w();
  w(`  Proof & Perspective — Proof block, issue ${opts.issue}`);
  w(`  run      ${RUN_PATH}`);
  w(`  kept     ${kept.length} of ${run.items.length} items`);
  w();
  kept.forEach((item, i) => {
    const url = citationUrl(item);
    const via = item.directUrl?.trim() ? "direct" : "feed  ";
    w(`  ${String(i + 1).padStart(2)}.  ${item.title.slice(0, 62)}`);
    w(`      ${via}  ${hostOf(url)}  ${shortDate(item.published) || "undated"}  score ${item.score}`);
    if (item.angle?.trim()) w(`      angle  ${item.angle.trim().slice(0, 62)}`);
  });

  if (opts.check) {
    w();
    w("  checking links...");
    const results = await checkLinks(kept);
    for (const r of results) {
      if (!r.ok) warnings.push(`link check failed (${r.status}): ${r.url}`);
    }
    w(`  ${results.filter((r) => r.ok).length} of ${results.length} resolved`);
  }

  if (warnings.length) {
    w();
    for (const warning of warnings) w(`  !  ${warning}`);
  }

  w();
  w(`  ${kept.length} placeholder${kept.length > 1 ? "s" : ""} to fill: {{WHY_IT_MATTERS_1}}..{{WHY_IT_MATTERS_${kept.length}}}`);
  w();

  process.stdout.write(`${render(kept, run)}\n`);
}

main().catch((error) => die(error?.stack ?? String(error)));
